version: "3.8"

services:
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3030:3030"
    volumes:
      - ./server:/app/server
      - ./shared:/app/shared
      - /app/server/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3030
    command: bun --watch src/index.ts

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app/client
      - ./shared:/app/shared
      - /app/client/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:3030
    depends_on:
      - api

networks:
  default:
    driver: bridge
