### Sign Up User
POST http://localhost:3030/api/auth/signup
Content-Type: application/json

{
    "email": "fernandorochaworld@gmail.com",
    "password": "password"
}

### Sign In User
POST http://localhost:3030/api/auth/signin
Content-Type: application/json

{
    "email": "fernandorochaworld@gmail.com",
    "password": "password123"
}

### Sign Out User
POST http://localhost:3030/api/auth/signout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsImtpZCI6ImtmMXFJc1cxREdkNnI4T1giLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL2x5enVhbGhkYXptZ2dxenFmZXpoLnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiJlZWIxNGU5Ny04OWNjLTQ2MzQtYjg4NC00OTQ2NzY5ZmUwYjEiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzMwNDM5NjE4LCJpYXQiOjE3MzA0MzYwMTgsImVtYWlsIjoiZmVybmFuZG9yb2NoYXdvcmxkQGdtYWlsLmNvbSIsInBob25lIjoiIiwiYXBwX21ldGFkYXRhIjp7InByb3ZpZGVyIjoiZW1haWwiLCJwcm92aWRlcnMiOlsiZW1haWwiXX0sInVzZXJfbWV0YWRhdGEiOnsiZW1haWwiOiJmZXJuYW5kb3JvY2hhd29ybGRAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwaG9uZV92ZXJpZmllZCI6ZmFsc2UsInN1YiI6ImVlYjE0ZTk3LTg5Y2MtNDYzNC1iODg0LTQ5NDY3NjlmZTBiMSJ9LCJyb2xlIjoiYXV0aGVudGljYXRlZCIsImFhbCI6ImFhbDEiLCJhbXIiOlt7Im1ldGhvZCI6InBhc3N3b3JkIiwidGltZXN0YW1wIjoxNzMwNDM2MDE4fV0sInNlc3Npb25faWQiOiIyYjMxYTE0Mi04ZjNkLTQ0NjQtYjZjNi0yOTRmNmMyMjliNTEiLCJpc19hbm9ueW1vdXMiOmZhbHNlfQ._4T4GQqQNxcGvnXKc1NmF_AdaewMZ6qyJQLQ8csJ6ow


### check user session
GET http://localhost:3030/api/auth/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsImtpZCI6ImtmMXFJc1cxREdkNnI4T1giLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL2x5enVhbGhkYXptZ2dxenFmZXpoLnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiJlZWIxNGU5Ny04OWNjLTQ2MzQtYjg4NC00OTQ2NzY5ZmUwYjEiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzMwNDM5NjE4LCJpYXQiOjE3MzA0MzYwMTgsImVtYWlsIjoiZmVybmFuZG9yb2NoYXdvcmxkQGdtYWlsLmNvbSIsInBob25lIjoiIiwiYXBwX21ldGFkYXRhIjp7InByb3ZpZGVyIjoiZW1haWwiLCJwcm92aWRlcnMiOlsiZW1haWwiXX0sInVzZXJfbWV0YWRhdGEiOnsiZW1haWwiOiJmZXJuYW5kb3JvY2hhd29ybGRAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwaG9uZV92ZXJpZmllZCI6ZmFsc2UsInN1YiI6ImVlYjE0ZTk3LTg5Y2MtNDYzNC1iODg0LTQ5NDY3NjlmZTBiMSJ9LCJyb2xlIjoiYXV0aGVudGljYXRlZCIsImFhbCI6ImFhbDEiLCJhbXIiOlt7Im1ldGhvZCI6InBhc3N3b3JkIiwidGltZXN0YW1wIjoxNzMwNDM2MDE4fV0sInNlc3Npb25faWQiOiIyYjMxYTE0Mi04ZjNkLTQ0NjQtYjZjNi0yOTRmNmMyMjliNTEiLCJpc19hbm9ueW1vdXMiOmZhbHNlfQ._4T4GQqQNxcGvnXKc1NmF_AdaewMZ6qyJQLQ8csJ6ow


### delete user
DELETE http://localhost:3030/api/auth/delete/eeb14e97-89cc-4634-b884-4946769fe0b1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsImtpZCI6ImtmMXFJc1cxREdkNnI4T1giLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL2x5enVhbGhkYXptZ2dxenFmZXpoLnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiJlZWIxNGU5Ny04OWNjLTQ2MzQtYjg4NC00OTQ2NzY5ZmUwYjEiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzMwNDM5NjE4LCJpYXQiOjE3MzA0MzYwMTgsImVtYWlsIjoiZmVybmFuZG9yb2NoYXdvcmxkQGdtYWlsLmNvbSIsInBob25lIjoiIiwiYXBwX21ldGFkYXRhIjp7InByb3ZpZGVyIjoiZW1haWwiLCJwcm92aWRlcnMiOlsiZW1haWwiXX0sInVzZXJfbWV0YWRhdGEiOnsiZW1haWwiOiJmZXJuYW5kb3JvY2hhd29ybGRAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwaG9uZV92ZXJpZmllZCI6ZmFsc2UsInN1YiI6ImVlYjE0ZTk3LTg5Y2MtNDYzNC1iODg0LTQ5NDY3NjlmZTBiMSJ9LCJyb2xlIjoiYXV0aGVudGljYXRlZCIsImFhbCI6ImFhbDEiLCJhbXIiOlt7Im1ldGhvZCI6InBhc3N3b3JkIiwidGltZXN0YW1wIjoxNzMwNDM2MDE4fV0sInNlc3Npb25faWQiOiIyYjMxYTE0Mi04ZjNkLTQ0NjQtYjZjNi0yOTRmNmMyMjliNTEiLCJpc19hbm9ueW1vdXMiOmZhbHNlfQ._4T4GQqQNxcGvnXKc1NmF_AdaewMZ6qyJQLQ8csJ6ow


